### ISSUE TITLE
Admin commands including password visible in chat on live timings

### ISSUE THREAD

**Issue by zwer54** [JustaPenguin/assetto-server-manager#1007]
I have configured admin group on sTracker and when we enter the race, we are automatically logged in as admin which is great. Bad thing is, this generates a chat message /admin "password" into a live timings chat window visible to anyone. 
I would like to have an option to completely remove chat window from live timings page.

**Comment by Hecrer** [comment]
Thanks for this, we're already aware of it and it is fixed in #989, which will be included in the v1.7.8 release coming soon!

In the meantime you should be able to log in to the server using the admin password directly rather than using the admin command in chat/stracker.
