### ISSUE TITLE
plugins not being being wait()ed for;  causing defunct processes to linger

### ISSUE THREAD

**Issue by mayfield** [JustaPenguin/assetto-server-manager#1030]
When plugins are run they are started using `Cmd.Start()` but then when they are killed they never have `Cmd.Wait()` called.   This leads to defunct plugin processes on every restart.  Also it introduces a race condition where the old plugin will not be fully stopped before ASM potentially runs another one.  I've been actively looking into an issue where real penalty is not able to call `listen()` when restarted very quickly, as done by ASM.  That particular issue may be addressed by waiting for the plugin process to reap before starting it again. 

**To Reproduce**
1. Restart the server repeatedly and observe the leaked plugin processes.   In my case, it's `stracker` and `ac_penalty`.

**Expected behavior**
Plugin processes getting reaped via the `Cmd.Wait()` call.

**Screenshots**
![image](https://user-images.githubusercontent.com/139316/98427720-7b704480-205b-11eb-9869-ade944807b79.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.7.9 (Fedora Core 32)

**Comment by cj123** [comment]
fixed in #1031
