### ISSUE TITLE
Concurrent Map Writes

### ISSUE THREAD

**Issue by uol-jdb50** [JustaPenguin/assetto-server-manager#1046]
This has occurred a couple of time in the last few days. The server manager crashes due to concurrent map writes. The console output is very long but the top section looks as follows:

![image](https://user-images.githubusercontent.com/43732832/101520198-08b8f880-397c-11eb-9028-3b1dd6d1332c.png)

**Comment by cj123** [comment]
hi, could you post more of the error (below the 'concurrent map writes'? Otherwise we can't see the cause of it

**Comment by uol-jdb50** [comment]
Of course
![image](https://user-images.githubusercontent.com/43732832/101520560-9563b680-397c-11eb-9387-0c7e0f417298.png)
![image](https://user-images.githubusercontent.com/43732832/101520643-b0362b00-397c-11eb-95be-61b276b7625a.png)

Hope this helps!

**Comment by cj123** [comment]
Thanks! Looks like an easy fix. It'll be in our next release :)

**Comment by uol-jdb50** [comment]
Excellent, thank you so much! Is there anything we can do in the mean time to prevent the issue, maybe avoid certain weather conditions as the issue seems to reference?

**Comment by cj123** [comment]
I think the issue only occurs if several weather related things occur at the same time. We run a lot of servers and haven't seen this crash once. It is very strange!
