### ISSUE TITLE
Check Sum error when using Evo190

### ISSUE THREAD

**Issue by AndyMonster** [JustaPenguin/assetto-server-manager#1062]
It appears AC as of Sept 2020 had an update that was to version 1.66 and requires host server to be updated as well, otherwise the 190Evo is effected and unable to use.  This is the error I get after being kicked.

Error might have something to do with:  00007FFD44455F86 (ntdll): (filename not available): RtlWaitOnAddress 00007FFD444315B4 (ntdll): (filename not available): RtlEnterCriticalSection 00007FFD444313E2 (ntdll): (filename not available): RtlEnterCriticalSection 00007FFD1B1E033B (DINPUT8): (filename not available): GetdfDIJoystick 00007FFD1B1E0804 (DINPUT8): (filename not available): GetdfDIJoystick AC\inputdevice.cpp (127): InputDevice::setG27Leds 00007FFCA42B539B (DWrite): (filename not available): lj_sampleSHimpl AC\inputdevice.cpp (88): InputDevice::~InputDevice AC\directinput.cpp (38): DirectInput::~DirectInput 00007FF6CB9AEA84 (acs): (filename not available): DirectInput::`scalar deleting destructor' AC\directinput.cpp (84): DirectInput::cleanup AC\game.cpp (233): Game::shutdownObject AC\game.cpp (221): Game::run AC\acs.cpp (477): wWinMain f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c (618): tmainCRTStartup 00007FFD437F7034 (KERNEL32): (filename not available): BaseThreadInitThun

**Comment by Nedla1969** [comment]
HI Andy, I had  a issue with the Merc evo on my server i tried another track and it was fine, Reinstalled the track i had the checksum on and all working,,  JYI.

**Comment by cj123** [comment]
The 1.66 update changed a whole bunch of cars. As @Nedla1969 commented, these issue can be quickly resolved by reuploading the track or car to the server.
