### ISSUE TITLE
Assetto Corsa Server Manager fails when daemonised

### ISSUE THREAD

**Issue by Jihakuz** [JustaPenguin/assetto-server-manager#1066]
**Describe your problem**
Maybe I am missing something but when I point a systemd service file at the linux binary, it always fails. Directly launching the binary works though.

**To Reproduce**
Add the service file below to your service file directory and type
systemctl start "whatever you called your file"

**Expected behavior**
The server manager will start with the same behaviour as launching it directly.

**Screenshots**
Here are the logs and the service file:

_error_
The error occurred attempting to: Read configuration file (config.yml)
The error more specifically is: open config.yml: no such file or directory

_service file_
[Unit]
Description=Assetto Corsa Server Manager Daemon
After=syslog.target network.target

[Service]
User=steam
Group=steam
Type=simple
ExecStart=/path/to/my/binary/server-manager
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target

**Desktop (please complete the following information):**
 - OS: centos 7
 
**Additional context**
N/A

**Comment by cj123** [comment]
In your `[Service]` section, make sure that you have a WorkingDir assigned as follows:

```
WorkingDirectory=/path/to/servermanager/data
```

And try again!
