### ISSUE TITLE
Error: Trying to load DRS zones -> panic: invalid argument to Intn

### ISSUE THREAD

**Issue by irudoy** [JustaPenguin/assetto-server-manager#1071]
**Describe the bug**

Got this error when starting the custom race. The server goes offline after that. Recently started to happen with any track/setup.
Custom races that were created a long time ago work fine, but if you change something, an error appears.

Server Logs:

```
Trying to load DRS zones from: content/tracks/ks_nurburgring/layout_gp_a/data/drs_zones.ini
Loading ZONE_0 {0.738 0.871}
Loading ZONE_1 {0.979 0.096}
panic: invalid argument to Intn
goroutine 1 [running]:
math/rand.(*Rand).Intn(0x18712200, 0x0, 0x6)
	c:/go/src/math/rand/rand.go:141 +0xa3
math/rand.Intn(0x0, 0x3c)
	c:/go/src/math/rand/rand.go:276 +0x2b
main.UpdateWeather()
	D:/dev/kunosprivate/go/src/acServer/weather.go:61 +0x2e
main.initServerCfg()
	D:/dev/kunosprivate/go/src/acServer/ac_server.go:1679 +0x20b0
main.main()
	D:/dev/kunosprivate/go/src/acServer/ac_server.go:269 +0x6e6
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 (host machine for Docker container)
 - Version 1.7.9 Multiserver, 1.7.9-1

**Comment by irudoy** [comment]
Seems it was fixed in 2.0.0

**Comment by lubbo** [comment]
> Seems it was fixed in 2.0.0

Maybe, but version 2.0.0 is not on this repo!

**Comment by adriadam10** [comment]
where is the 2.0.0 version?

**Comment by irudoy** [comment]
@adriadam10 it's not open-source now

https://emperorservers.com/products/assetto-corsa-server-manager
