### ISSUE TITLE
When starting a race on a custom map with mod cars and legit cars, server crashes,

### ISSUE THREAD

**Issue by TFujiwara** [JustaPenguin/assetto-server-manager#1073]
**Describe the bug**
When starting a race on a custom map with mod cars and legit cars, server crashes,

**To Reproduce**
1. Create a custom race
2. Add mod cars and legit cars'
3. Save and start the server

**Expected behavior**
Expected that the server started sucessfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/10372989/109397531-56b81980-7937-11eb-8873-f70e96e76312.png)

**Desktop (please complete the following information):**
 - OS: Debian 10

**Comment by cj123** [comment]
Hi, it seems that you do not have any sessions configured in your event setup. Please enable one session, e.g. practice/qualify/race and try again.
