### ISSUE TITLE
Admin commands are not forwarded to udp plugins

### ISSUE THREAD

**Issue by TheStraing** [JustaPenguin/assetto-server-manager#1076]
**Describe the bug**
It seems like that the original ac server forwarded admin commands (starting with /) to udp plugins like normal chat messages.
Plugins like Kissmyrank used this behavior to mask their commands so they couldn't be seen by other users.
(Example the /kmr login <password> command or the /kmr applink command)
With the new server manager v2.0.4, It seems like this doesn't happen anymore so commands like the ones above do not work.

**To Reproduce**
1. Setup a KMR instance with Server manager
2. Test the above commands

**Expected behavior**
The commands should be intercepted by udp plugins like KMR and should be able to respond.

**Comment by cj123** [comment]
This is fixed in v2.1.0
