### ISSUE TITLE
Server Rating

### ISSUE THREAD

**Issue by Hecrer** [JustaPenguin/assetto-server-manager#226]
Similar to iRacing safety system.

Clean races ++
Lots of crashing/cuts --

Events have an option to only allow entrants with a minimum server rating.

(KissMyRank may already implement this - if it does not much point in us doing it)

**Comment by luismercury** [comment]
We (Our league CSR) consider it very important that this included in assetto-server-manager.

obviously, as low priority.

Thank a lot.

**Comment by cj123** [comment]
see: https://acsr.assettocorsaservers.com ;)
