### ISSUE TITLE
Server Manager not recognizing acServer crash

### ISSUE THREAD

**Issue by port22** [JustaPenguin/assetto-server-manager#542]
As I read here, there is some kind of scheduler in the app.
Could it perhaps be used to monitor the currently running `acServer` process?
Currently, if acServer crashes unexpectedly, server-manager will not notice, even with Auto-Loop'ed events, so it does not start a new process anytime soon.

My proposal: 
On starting a acServer process, server-manager should record the pid so it knows it should be running.
If a scheduler at any time finds that the acServer process is not running anymore, schedule a restart the next time the check will still not find a process (every minute should be very enough) and record the new pid.
In case a new acServer has been started, read the server_cfg.ini properties to provide the webinterface with correct data.

Normally I would do it with something external, like monit. But then still server-manager would not know nothing about it, and we want correct data in the webinterface, right?

That would make it possible to start and stop acServer from outside server-manager (because I can't get the custom/load route working, see https://github.com/cj123/assetto-server-manager/issues/516#issuecomment-538745257) and also provide simple monitoring.

That's the main reason I switched from acweb to server-manager, because starting/stopping from outside the app was not possible.

**Comment by cj123** [comment]
fixed in #725
