### ISSUE TITLE
Driver swaps For endurance

### ISSUE THREAD

**Issue by Machacador1996** [JustaPenguin/assetto-server-manager#553]
There is an external aplication called fairracing, that control the drivers swaps, and minimun pit stop time for people, to avoid people with faster pc, do a faster driver change... My question is, it's posible that the server keep the number of laps made by a guy in a endurance race, and when the car is driven by the mate of his team, keep those laps and race position in a ingame app?
there's the link of the app --> https://www.racedepartment.com/downloads/fairracing-minimum-stoppage-time-for-driver-swaps.16440/

I'm a informatic ingeniering student from first year of university. By the moment, only know C and C++.... a bit of python. But never worked on big projects.

**Comment by cj123** [comment]
fixed in #809
