### ISSUE TITLE
Stracker not reachable with multiserver

### ISSUE THREAD

**Issue by TheStraing** [JustaPenguin/assetto-server-manager#668]
Hi,
I cannot reach the STracker Page through server manager where using the new multiserver software.
I guess this is caused by the fact that you don't connect directly to the single server manager instance anymore.

**Comment by cj123** [comment]
Hi, I think this is due to each individual server assetto folder not having the stracker folder in it. We'll release an update to fix it, but for now you can do this manually by creating a copy of your stracker folder inside each servers/SERVER_XX/assetto folder

**Comment by TheStraing** [comment]
I have already done this.
In fact, I was able to start the stracker server (I could see it from the logs) but I couldn't reach the stracker pages through server manager.
So I opened a specific port for the stracker web server (and set stracker up accordingly) so I could connect directly to it.

**Comment by cj123** [comment]
@TheStraing does v1.6.1 fix this issue for you?

**Comment by TheStraing** [comment]
well, now It's reachable but Icons and Live Map are broken when I connect through server manager.
If I use the stracker port directly, It does work well without any problems...

**Comment by cj123** [comment]
I'm marking this as fixed through the new method of linking directly to the stracker panel. Check out "Public URL" in the stracker options.
