### ISSUE TITLE
Integrate "AC Penalty Tools"

### ISSUE THREAD

**Issue by luismercury** [JustaPenguin/assetto-server-manager#677]
https://www.racedepartment.com/downloads/ac-penalty-tool.29591/

The best is a page with all penality settings.
Similar to sTracker.
![image](https://user-images.githubusercontent.com/48275749/70649396-cd320400-1c2b-11ea-8f36-a26a0c74413f.png)

a "copy" of penalty_settings.ini + ac_settings.ini (for the page)

if you start  a session start: ac server, stracker, penalty tool (+ other plugin)
the other settings of the plugin are constant and edit from the page is not needed
only the session and penalty settings are very important.

Easy! A new page with all settings of this two files

[Setting1and2.zip](https://github.com/cj123/assetto-server-manager/files/3952078/Setting1and2.zip)

**Comment by ennimann** [comment]
Hi,
that whould be great!

**Comment by xaviortiz** [comment]
Hi, sound great.  We use it too.

regards

**Comment by cj123** [comment]
fixed in #914
