### ISSUE TITLE
live timing

### ISSUE THREAD

**Issue by ixnis79** [JustaPenguin/assetto-server-manager#683]
Hello. we are using Assetto Corsa Server Manager Premium v1.6.1 and are having trouble with live timing. there is some solution to this problem? we did the last update, but the problem remains

**Comment by cj123** [comment]
hi - can you give us more information?

1) what is the problem exactly?
2) what steps do you take to make the problem happen?
3) what OS is server manager hosted on?
4) have you always had this issue, or has it appeared in a recent update?

**Comment by ixnis79** [comment]
Good morning.  The name is assettozeusteam.gr . When we make the last up
date the daily practice  does not show. The live timing is not working. We
can not see in the site who is in the track and what timing has . Sorry for
my English.

Στις Πέμ, 19 Δεκ 2019, 01:25 ο χρήστης Callum Jones <
notifications@github.com> έγραψε:

**Comment by Hecrer** [comment]
Hi,

You say the practice doesn't show, is it not running on the server at all?

Again i think it would be best if we could have a look at your server manager install, if you don't mind the easiest way to figure it out would be to direct message one of us on our Discord with the server details (https://discordapp.com/invite/6DGKJzB).
