### ISSUE TITLE
live timings: data persist causes panic

### ISSUE THREAD

**Issue by cj123** [JustaPenguin/assetto-server-manager#700]
![image](https://user-images.githubusercontent.com/306873/71982291-0dc97100-321c-11ea-8091-b9893f793be9.png)

**Comment by dadebolo** [comment]
One more time the same error on another pc, Multiserver Premium, one server running.
I hope it can help you.

![image](https://user-images.githubusercontent.com/53077855/72194183-f4d3e200-340c-11ea-9abc-6278578666ed.png)

**Comment by cj123** [comment]
fixed in #742
