### ISSUE TITLE
geoIP() returns IPv6 address for join link. Suggestion: Add override setting

### ISSUE THREAD

**Issue by mazzn** [JustaPenguin/assetto-server-manager#746]
### Issue

The Ubuntu server on which I run my acServer and Server Manager instance comes with both IPv4 and IPv6 connectivity (dual stack). Assetto Corsa does unfortunately not work with IPv6, but my server's IPv6 address is returned by the service used in the [`geoIP()`  method](https://github.com/JustaPenguin/assetto-server-manager/blob/dfb23162f010bdd8fdaeedfa29814ea883ffcb9f/content_manager_wrapper.go#L526) and ends up in the join link for Content Manager, which won't work for several reasons - primarily AC's apparent lack of IPv6 support.

It seems IPv6 is the preferred network connection on my machine and therefore the request to the GeoIP service returns it's IPv6 address. Simply turning off IPv6 connectivity is not an option.

### Proposal

My first idea was to force requests sent to the GeoIP service to use IPv4 (or use one that only supports IPv4, which really sucks as a workaround). This could be problematic though, since it will force Server Manager to take control of network operations that were previously handled by `http.Get()`, and it could be hard to implement properly cross-platform, too. I sadly don't know much about Go, otherwise I'd try to come up with a fix. While there [seem to be possible workarounds](https://stackoverflow.com/questions/53055808/golang-force-net-http-client-to-use-ipv4-ipv6), I have no idea how feasible they are.

Instead, I would like to see some sort of override functionality for the join link. Not only will it allow to get around this issue with dual stack setups, but can potentially even help in avoiding problems involving multiple network adapters and stuff like VPN tunnels, where you could also get a wrong IP address returned from the GeoIP service. Additionally, a server's link generation won't break if the service is either not available or restricted by network policies/firewall/proxy/etc.

I would be very happy with the option to set this in the `config.yml`, but a setting in the _Content Manager Integration_ section would be quite nice, too. Attached you can find a sketch of what I imagined.

![servermanager-ipoverride](https://user-images.githubusercontent.com/5346077/73198879-20a4d680-4134-11ea-82fd-dfd8b8a0061e.jpg)
⬆️ Don't try to join that server, it's Wikipedia's webserver :)

**Comment by cj123** [comment]
fixed in #750. Thanks again!
