### ISSUE TITLE
populateTyreDropdown in manager.js causes long delays when adding a lot of cars to a custom race

### ISSUE THREAD

**Issue by Thracky** [JustaPenguin/assetto-server-manager#781]
**Describe the bug**
When configuring a custom race, each time a car is added the populateTyreDropdown() function gets called. On line 527 it enters a for loop to iterate through all the cars and inside this loop is a call to multiSelect('refresh');

This multiSelect call seems to be a bit on the expensive side but the main issue is each time you add a car it takes longer and longer to complete this loop, to the point where adding another car when you have say, 100, can take several seconds to complete.

**To Reproduce**
1. Create a new custom race
2. Start adding cars, lots of them :)
3. You will eventually notice that clicking on a car takes a LONG time for the car to be added. You can use the performance tab in chrome to record what happens during a click and observe that the vast majority of the time is spent inside populateTyreDropdown() calling multiSelect().

**Expected behavior**
Adding a car should not take several seconds to process in the browser.

**Screenshots**
Here's a screenshot from the performance recording, noticing that single calls to populateTyreDropdown() are taking several seconds to complete:
![image](https://user-images.githubusercontent.com/2881908/74592457-a909ef00-4fef-11ea-98be-64d5ffbdf4d1.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Brave (Chromium based)
 - Version [e.g. 22] 1.4.86

**Comment by Thracky** [comment]
Closed as I see this behaviour is likely not going to be encountered due to AC limiting car choices to entrant list.

**Comment by cj123** [comment]
Hey!

Firstly, i'd like to thank you for the detailed bug report - i'm pretty motivated to take a look into this regardless of your reason for closing!

I have noticed a performance dip through calling `multiSelect("refresh")` - i'm sure there are some easy wins here, so i'm going to reopen this. 

Thanks for your contribution!
