### ISSUE TITLE
Event result given points in championship are wrong

### ISSUE THREAD

**Issue by SystemFuchs** [JustaPenguin/assetto-server-manager#787]
**Describe the bug**

We are driving a championship. Driver was 5th in the second race, regarding our point reference the driver gets 11 points. In the event results the driver gets only 8 points. The driver was given a penalty of three points in the first race. It seems, that the penalty is applied to the event result in the following event again.

The overall championship results are fine allthough!

You can take a look at 

http://raceserver.sim4race.com:8780/championship/59f33754-8b8d-41b1-bf52-4f8b401e9a66

and take a closer look at the second event at Nuerburgring.

**To Reproduce**
1. Define championship
2. Drive an event
3. Apply a penalty to a driver
4. Drive a second event
5. Check result table for that specific event

**Expected behavior**
Penalty is only applied one time

**Screenshots**
![Snag_a330785](https://user-images.githubusercontent.com/3988026/74928668-3f685700-53da-11ea-8af9-078594e89344.png)
![Snag_a331a42](https://user-images.githubusercontent.com/3988026/74928674-42634780-53da-11ea-9f0f-4ddbe4b82047.png)
![Snag_a332a50](https://user-images.githubusercontent.com/3988026/74928683-44c5a180-53da-11ea-8806-8ea7523cf453.png)
![Snag_a33358b](https://user-images.githubusercontent.com/3988026/74928684-45f6ce80-53da-11ea-93f3-44f5603eef84.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Browser chrome
 - Version 80.0.3987.116

**Comment by cj123** [comment]
Hi! Thanks for the detailed bug report!

It definitely looks like something is incorrect here - we can fix it for our next update.
