### ISSUE TITLE
Server manager settings gone after docker-compose down

### ISSUE THREAD

**Issue by maeries** [JustaPenguin/assetto-server-manager#835]
**Describe the bug**
Server-Manager settings get deleted when `docker-compose down` is executed

**To Reproduce**
1. Install server and server-manager using the example docker-compose.yml
2. `docker-compose up -d`
3. Change some stuff like setting an admin password or create custom races
4. `docker-compose down` and `docker-compose up`

**Expected behavior**
I should be able set login with the password, set before and the custom races should still be there.

**Actual behavior**
I need to login with _admin_ and _servermanager_ and the saved custom races are gone. The results are still there, though.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version 74

**Comment by cj123** [comment]
Ah, seems we're missing an extra volume in the README. Try volume mounting your server manager database in the docker-compose.yml, or setting your store path in config.yml to be inside the assetto server folder (so that it is volume mounted). I'll amend our readme!

**Comment by maeries** [comment]
So, I decided to just mount the entire folder, i.e. I replaced the volumes section with just:
```
    volumes: 
    - ./data:/home/assetto/server-manager
```
The strange thing is that `home/assetto/server-manager/assetto` inside the docker container is empty, even though `./data/assetto` contains the server files. This results in the server manager trying to install the server again which fails, because steamcmd is not installed.
A test file I created in `./data/test` shows up correctly

**Comment by maeries** [comment]
I just found a workaround. I renamed `./data/assetto` to `./data/assetto-server` and also changed the `install_path` from _assetto_ to _assetto-server_.

The Problem seems to be that something creates the directory `/home/assetto/server-manager/assetto` in the container which then conflicts with the mounted _assetto_ directory
