### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Robbe1612** [JustaPenguin/assetto-server-manager#885]
**Describe the bug**
I'm trying to make this app work but whenever I open acServer.exe it keeps giving me '
RESPONSE: ERROR,INVALID SERVER,CHECK YOUR PORT FORWARDING SETTINGS
CONNECTION TO LOBBY FAILED, ATTEMPT NUMBER 1' and some more stuff. When I try to launch the server with acservermanager.exe it just stays on
Starting AC Server...

**Expected behavior**
It should start right away now.

**Screenshots**

![image](https://user-images.githubusercontent.com/64539051/80648263-2a5e1300-8a70-11ea-9d20-2282b75bd87b.png)

![image](https://user-images.githubusercontent.com/64539051/80648323-4497f100-8a70-11ea-8140-14f77207acc3.png)

**Desktop (please complete the following information):**
 - OS: windows 1903
 - Browser chrome
 - Version newest

**Comment by cj123** [comment]
This is an issue with your port forwarding settings. I would recommend looking up a guide on port forwarding. You need to forward the HTTP, TCP and UDP ports that you have set for the server to run. 

I imagine if you look in logs/session/output*.log you'll see the same error.

**Comment by Robbe1612** [comment]
Thank you, I will look into that.

**Comment by Natlafrite** [comment]
Hello Robbe1612, How did you solve your problem?
I am having the same problem and I haven't figured out how to solve it.

**Comment by Robbe1612** [comment]
I'm sorry but I never did, I just ended up hiring a server at emperor servers, it was really cheap and easy.

**Comment by Natlafrite** [comment]
Okay, thanks for your reply, have a nice day!
