### ISSUE TITLE
Avoiding browser password auto-fills on /server-options page

### ISSUE THREAD

**Issue by cjoneill** [JustaPenguin/assetto-server-manager#897]
**Is your feature request related to a problem? Please describe.**
This is something caused by user agents (browsers), so I'm calling it a FR rather than a bug _per se_.  

The "password" field for restricting driver access to races is handled by HTML which Google Chrome identifies as a _user_ password field, and if the admin has saved their login within Chrome's native password store, it will auto-fill this field. I've not tested browsers other than Chrome or pluggable credential manager extensions etc but I'd imagine the potential problem is wider than just Chrome.

Screenshot below.

The outcome is a high probability that, unless that field is manually cleared by the admin user each time the page is loaded, any form submission there could set a racing password requirement, equal to the admin user's own UI password.

That then presents a potential a security problem because _another_ admin user who loads that form will have the plaintext UI password for the _first_ admin user pre-populated in the HTML, this time from the server side.

**Describe the solution you'd like**
Refactor the `password` field in that form in a way that discourages password managers from auto-filling the field. The proper use of the `autocomplete` attribute is actually notoriously difficult because browsers [violate](https://stackoverflow.com/questions/23646953/stop-browser-from-auto-filling-the-form-username-and-password-fields) the [W3C's spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill). Some recommend using [`new-password`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-new-password) as the `autocomplete` attribute's value, which might work.

**Describe alternatives you've considered**
Given that the plaintext password is pre-populated in the form when a password exists, as implemented today, the additional security afforded by using `type=password` in the `input` element at all is arguably of minimal value, beyond avoiding revealing the text while someone's beside the admin's screen or viewing a screen share etc. There are already potentially sensitive credentials or info available on that screen too, e.g. the Discord token. As such, an alternative is simply altering the field to be plaintext-viewable rather than masked by dots. That might just shift the problem to the next ("Admin Password") field, I don't know  ¯\\\_(ツ)\_/¯

I'm honestly not sure which of these two alternatives (messing with getting the current fields to behave, or ignoring the sensitivity of the password at all) I prefer! 

**Additional context**
![server-options-path-prefilled-pw-chrome](https://user-images.githubusercontent.com/2287514/81526242-6e1f1980-939a-11ea-9ac5-b0f1c25e5b5d.png)

**Comment by cj123** [comment]
Hey! Firstly, thanks for the incredibly detailed issue!

I'm tempted to lean towards the `autocomplete="new-password"` solution. It seems like it's [supported well enough for our use case](https://caniuse.com/#feat=mdn-html_global_attributes_autocomplete_new-password). I do understand the argument for just showing them in plaintext, but I like the UX of getting a password prompt for a password field.

This would also need adding to Championships and Custom Races (and maybe Race Weekend Sessions too?) where password override fields are shown.

Adding to our next milestone!
