### ISSUE TITLE
Tyres are not recorded unless content added via upload

### ISSUE THREAD

**Issue by cjoneill** [JustaPenguin/assetto-server-manager#908]
**Describe the bug**
When you upload car mods, one of either of the functions `addTyresFromDataACD()` or `addTyresFromTyresIni()` [runs](https://github.com/JustaPenguin/assetto-server-manager/blob/master/content_upload.go#L122), detecting which tyres are applicable for the mod and [adding](https://github.com/JustaPenguin/assetto-server-manager/blob/master/content_tyres.go#L176) them to `mod_tyres.ini`. 

If content is added directly to the server back end and subsequently search-indexed, the tyres aren't mapped because those functions don't run and the cars therefore can't be used.

**To Reproduce**
1. unzip/rsync/etc a valid car directory straight to the `<somedir>/content/cars/` directory
2. Manually reindex from the `server-options` path in a browser
3. View the `/car/<car_directory>` path in the browser and see nothing under "Tyres" in the sidebar OR verify `mod_tyres.ini` doesn't change.

**Expected behavior**
Reindexing search (or waiting for `scan_content_folder_for_changes: true` to do its job) should correctly detect and add tyre data to the server. 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04
 - Browser - all
 - Version (server: 1.7.4 Premium)

**Additional context**
n/a

**Comment by cj123** [comment]
Hey! Thanks for reporting this. Looks like an easy one to get into the next release.
