### ISSUE TITLE
AC Server Manager is not compatible with Real Penalty Tool beta version 3.0.b02

### ISSUE THREAD

**Issue by neliomarcelino** [JustaPenguin/assetto-server-manager#918]
AC Server Manager is not compatible with AC Real Penalty 3.0.b02.
When copying all the AC Real Penalty from beta version files to "realpenalty" in "assettocorsa" directory, AC Server Manager does not detect on the configuration page, although with the stable version works fine.

Link to download 3.0.b02 Beta version:
[https://drive.google.com/file/d/1u8B0CXn4PvqVX2aboJN7Z56V6P_jVZCH/view](url)

Got this link from their Discord Server.

**Comment by cj123** [comment]
as of the next release, real penalty v3.00.02 will be supported.
