### ISSUE TITLE
Import renamed result file indefinitely breaks results view

### ISSUE THREAD

**Issue by ejustice** [JustaPenguin/assetto-server-manager#944]
**Describe the bug**
When uploading a result file with a modified name, the file uploads but any get attempt then gives a 500.

**To Reproduce**
1. Go to /results
2. Click on BrowseResult / upload result file
3. select a result file with a different name than original, for example, my result file was called peugeot206_RACE_2_2020_5_10_17_47_RACE.json instead of 2020_5_10_17_47_RACE.json
4. file is uploaded, and /results now gives a 500. Without any possibility to fix the issue.

**Expected behavior**
- either the file should not be stored if name is invalid
- or file should be ignored
in any case, it should not break the view :-)

**Screenshots**
not relevant

**Desktop (please complete the following information):**
not relevant

**Additional context**
My currently broken view can be found here:
https://knutselracing.assettocorsaservers.com/results

**Comment by cj123** [comment]
thanks for the report! this was fixed in #945, and will be in our next release :)
