### ISSUE TITLE
Live Timing/Map Functionality

### ISSUE THREAD

**Issue by EXYZED** [JustaPenguin/assetto-server-manager#975]
**Describe the bug**
Ver 1.7.6

Existing live timing issue with ACSM - Driver dots appear on the bottom right of the map - speedometer information can not be obtained through site.

- Driver is outside of pits
- Firewalls have been disabled for the server.
- **Crashes and their locations are however registered, see screenshots**

Site is hosted using Amazon EC2 with a HTTP load balancer

### Browser
![image](https://user-images.githubusercontent.com/18582414/89103384-60ad8480-d409-11ea-97df-aeed621f2f9b.png)
![image](https://user-images.githubusercontent.com/18582414/89103594-c2bab980-d40a-11ea-9063-722737dee6c8.png)

![image](https://user-images.githubusercontent.com/18582414/89103395-8aff4200-d409-11ea-8d6d-a03f8fdd35f5.png)

Web Console warnings/error - timeouts display upon player join and disconnect. 
### Executable
![image](https://user-images.githubusercontent.com/18582414/89103419-bd10a400-d409-11ea-87bc-45486f09d663.png)

**Comment by cj123** [comment]
Hi! Does this issue occur without the use of a HTTP load balancer? I wonder if it's causing some messages to get lost or something? I've never used a load balancer with Server Manager

**Comment by EXYZED** [comment]
@cj123 Thanks for getting back-

Can confirm that the issue still persists without the use of a HTTP/HTTPS Load Balancer (LB is deactivated).

- We have allowed all network traffic in and out temporarily in attempt to resolve this issue on our VM,
- Firewalls on the VM have been disabled, no antivirus.
- Attempted to check on different browser platforms to see if it's exclusively a browser issue (not the case).

If it helps, my Discord username is `#Antoan0001` if you need to PM + I can give you a remote desktop connection to our server if you feel the need.
