### ISSUE TITLE
Checksum fail with Kunos cars

### ISSUE THREAD

**Issue by dkgorace** [JustaPenguin/assetto-server-manager#983]
Not sure why or how this started, worked fine for 3 weeks in Championship series. Then yesterday everyone gets a checksum fail with a Kunos car...{Tatuus FA1}

Mod track, Donington. Everyone has the same track and version.

My other set server works for practice..I.E. mod track {1966 Spa}..Kunos cars...{ Ferrari '67 312 and Lotus 49 }

 - OS: Windows 10
 - Browser Chrome

**Comment by Hecrer** [comment]
This car was updated in the latest update for Assetto Corsa (7th August 2020). Deleting the car from the server and then uploading your local copy on the Content -> Cars page should fix this issue!

**Comment by dkgorace** [comment]
Wow! Super fast reply!! Cheers, I'll give it a go.

**Comment by dkgorace** [comment]
Well, that was easy. I didn't want to make things worse by deleting and reinstalling as my mates server is in the same problem but won't reinstal car at all.
...................... Case closed.
